### ISSUE TITLE
Error: Please use "npm start" to start the server! Even when using npm start

### ISSUE THREAD

**Issue by Echo-Script** [Robin-floss/bcrypt-express-login#1]
Title explains it pretty much - it tells you to use npm start when you're already using it

**Comment by Robin-Sch** [comment]
https://github.com/RobinSchapendonk/bcrypt-express-login/blob/77555e71310a7ae0485961bd6a5c70d0d6062535/index.js#L20

Do you have a .env file with the credentials?
